import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "./Components/footer";
import SidebarDemo from "./Components/sidebar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "My Next.js App",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex flex-col h-screen`}
      >
        <div className="flex flex-1">
          <SidebarDemo />
          <div className="flex-1 flex flex-col overflow-y-auto">
            <div className="flex-1 min-h-screen">{children}</div>
        <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
